Add missing requirement
homersoft/oadr2-ven-python pull request #8
Opened 2020-08-27 13:11 UTC by rafalgajda-silvair

This patch aligns the VEN behavior with specification and adds method for opting out of the event.

2020-08-28 09:05 UTC, bartoszflis-silvair reviewed
Do we have any unit tests for that?

2020-08-31 07:06 UTC, michallowasrzechonek-silvair requested changes

2020-08-31 07:06 UTC, michallowasrzechonek-silvair commented on oadr2/event.py
> +        if e_id not in self.db.get_active_events().keys():
I don't think `.keys()` is needed here:

```
>>> 1 in {1: "one", 2: "two"}
True
>>> 3 in {1: "one", 2: "two"}
False
```

2020-08-31 07:06 UTC, michallowasrzechonek-silvair commented on oadr2/event.py
> +            if evt in self.optouts:
https://docs.python.org/3.7/library/stdtypes.html#frozenset.discard

2020-08-31 11:16 UTC, rafalgajda-silvair commented on oadr2/event.py
> +            if evt in self.optouts:
Changed

2020-08-31 11:17 UTC, rafalgajda-silvair commented on oadr2/event.py
> +        if e_id not in self.db.get_active_events().keys():
Changed

2020-09-01 12:46 UTC, michallowasrzechonek-silvair approved these changes

2020-09-02 07:30 UTC, merged